# Site settings
title: Huang Qiheng
name: Huang Qiheng
subtitle: Student
email: huangqh29@mail2.sysu.edu.cn
description: >
  Student
baseurl: ""
url: "https://philipwelia.github.io/HuangQiheng.github.io/"
github_username:  Huang Qiheng
disqus_baseurl: "https://philipwelia.github.io/HuangQiheng.github.io/"
disqus_shortname: https-HuangQiheng-github-io
permalink: :title
#google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Huang Qiheng"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: Huang Qiheng
    url: https://philipwelia.github.io/HuangQiheng.github.io/
    desc: Fork me on GitHub
    share: false

  - name: ResearchGate
    icon: researchgate
    username: Huang Qiheng
    url: https://linkedin.com/pesoto
    desc: Connect with me on LinkedIn
    share: true
